name: Elixir CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: elixir:1.9.4

    steps:
      - uses: actions/checkout@v1

      - name: Cache Dependecies
        id: cache-deps
        uses: actions/cache@v1
        with:
          path: deps
          key: ${{ runner.os }}-mix-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}
          restore-keys: |
            ${{ runner.os }}-mix-

      - name: Cache Dialyzer PLTs
        id: cache-plts
        uses: actions/cache@v1
        with:
          path: priv/plts
          key: ${{ runner.os }}-plts
          restore-keys: |
            ${{ runner.os }}-plts

      - name: Install Dependencies
        run: |
          mix local.rebar --force
          mix local.hex --force
          mix deps.get

      - name: Check Format
        run: mix format --check-formatted

      - name: Run Tests
        run: mix test

      - name: Run Dialyzer
        run: mix dialyzer --halt-exit-status

      - name: Build Code Coverage Report
        run: mix coveralls.json

      - name: Upload Code Coverage Report
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./cover/excoveralls.json
